export type StatKey = 'money' | 'mental' | 'health' | 'love' | 'family' | 'debt';
export type Stats = Record<StatKey, number>;
export type EndingKind = 'payday' | 'broke' | 'collapsed' | 'ghosted' | 'debt';
export type Choice = { text: string; sub: string; effects: Partial<Stats>; flag?: string; risk?: number };
export type Event = { id: string; title: string; scene: string; choices: Choice[]; tags: string[] };
export type GameState = { day: number; targetDay: number; stats: Stats; history: string[]; seed: number; used: string[]; over?: EndingKind };

export const initialStats: Stats = { money: 1150000, mental: 76, health: 78, love: 62, family: 60, debt: 0 };
export const rupiah = (n: number) => `Rp${Math.abs(Math.round(n)).toLocaleString('id-ID')}${n < 0 ? ' utang' : ''}`;

export const events: Event[] = [
 { id:'kos', title:'Ibu Kos Udah di Depan Pintu', scene:'Baru buka mata, pintu diketok. Suaranya kalem, tapi vibes-nya: "duit kos mana, bestie?"', tags:['rent'], choices:[{text:'Bayar setengah dulu',sub:'Sakit, tapi masih keliatan niat.',effects:{money:-450000,mental:-6,family:2}},{text:'Nego sambil muka bantal',sub:'Modal jujur dan rambut acak-acakan.',effects:{mental:-10,love:-2,money:-150000},flag:'nego kos'},{text:'Kepikiran pinjol',sub:'Cepat cair, cepat nyesel juga.',effects:{money:300000,debt:450000,mental:-12},flag:'pinjol'}]},
 { id:'makan', title:'Makan Apa Nih?', scene:'Perut bunyi dari tadi. Pilihannya: warteg, mi instan, atau sok kuat padahal lemes.', tags:['food'], choices:[{text:'Warteg ayam',sub:'Mahal dikit, badan bilang makasih.',effects:{money:-22000,health:9,mental:4}},{text:'Mi telur anak kos',sub:'Klasik. Tidak sehat, tapi mengerti keadaan.',effects:{money:-9000,health:-4,mental:2}},{text:'Skip makan dulu',sub:'Hemat sih. Tapi ini bukan flex.',effects:{health:-14,mental:-8,money:0}}]},
 { id:'transport', title:'Ojol Lagi Mahal Banget', scene:'Hujan pas jam pulang. Tarif ojol naik kayak harga diri setelah gajian.', tags:['transport'], choices:[{text:'Tetap ojol',sub:'Kering sampai rumah, saldo basah kuyup.',effects:{money:-38000,mental:-3,health:3}},{text:'Neduh di minimarket',sub:'Niat nunggu, ujungnya beli minum.',effects:{money:-14000,mental:3,health:-2}},{text:'Naik angkot random',sub:'Murah, tapi rutenya suka plot twist.',effects:{money:-8000,mental:-7,health:-3}}]},
 { id:'ortu', title:'Chat Rumah: “Ada Sisa?”', scene:'Ibu kirim foto genteng bocor. Kamu lihat saldo. Saldo langsung pura-pura mati.', tags:['family'], choices:[{text:'Kirim semampunya',sub:'Anak baik, dompet menipis.',effects:{money:-120000,family:14,mental:2}},{text:'Telepon dan jujur',sub:'Nggak langsung beres, tapi hati agak lega.',effects:{family:6,mental:7}},{text:'Bales nanti aja',sub:'Masalahnya nggak hilang, cuma pindah ke kepala.',effects:{family:-13,mental:-10}}]},
 { id:'date', title:'Dia Minta Quality Time', scene:'“Kita jarang jalan.” Kalimat pendek, efeknya panjang ke saldo.', tags:['love'], choices:[{text:'Piknik murah',sub:'Bawa tumbler, tetap manis.',effects:{money:-35000,love:12,mental:6,health:2}},{text:'Dinner beneran',sub:'Romantis, tapi rekening ikut nangis.',effects:{money:-180000,love:18,mental:3}},{text:'Bilang lagi capek',sub:'Jujur dikit, aman dikit, dingin dikit.',effects:{love:-10,mental:-4}}]},
 { id:'sakit', title:'Badan Mulai Nggak Enak', scene:'Kepala berat, tenggorokan aneh. Tapi kerjaan tetap sok penting.', tags:['health'], choices:[{text:'Beli obat terus tidur',sub:'Ini bukan malas. Ini maintenance.',effects:{money:-42000,health:15,mental:4}},{text:'Kerokan lanjut gas',sub:'Tradisi jalan, badan protes.',effects:{health:-5,mental:-6,money:0}},{text:'Ke klinik BPJS',sub:'Murah, tapi antreannya ngajak sabar.',effects:{money:-10000,health:11,mental:-4}}]},
 { id:'teman', title:'Diajak Nongkrong “Bentaran”', scene:'Bentaran versi teman-teman biasanya pulang pas kursi udah diangkat.', tags:['social'], choices:[{text:'Ikut, pesan es teh',sub:'Tetap hadir tanpa sok sultan.',effects:{money:-12000,love:2,mental:8,health:-1}},{text:'Ikut patungan full',sub:'Seru banget. Bayarnya juga banget.',effects:{money:-95000,mental:12,love:4}},{text:'Skip dulu',sub:'Hemat, tapi story mereka ganggu pikiran.',effects:{mental:-5,love:-3}}]},
 { id:'ban', title:'Ban Bocor di Gang', scene:'Motor oleng dikit. Tukang tambal ban muncul seperti NPC penyelamat.', tags:['chaos'], choices:[{text:'Tambal sekarang',sub:'Praktis, walau saldo kesentil.',effects:{money:-25000,mental:-3}},{text:'Dorong aja',sub:'Gratis, tapi betis ikut meeting.',effects:{health:-9,mental:-7}},{text:'Minta tebengan',sub:'Selamat, tapi punya utang budi.',effects:{love:5,mental:1,family:-1}}]},
 { id:'bonus', title:'Ada Rezeki Nyasar', scene:'Cashback masuk. Patungan ada sisa. Semesta tumben nggak jahat.', tags:['luck'], choices:[{text:'Simpan buat besok',sub:'Wah, karakter development.',effects:{money:85000,mental:3}},{text:'Bayar utang dikit',sub:'Kecil, tapi langkahnya bener.',effects:{debt:-90000,mental:7}},{text:'Beli martabak mini',sub:'Bahagia kecil, gula besar.',effects:{money:35000,mental:10,health:-2}}]},
 { id:'boss', title:'Bos Chat Malam-Malam', scene:'“Bisa revisi malam ini?” Bahasanya sopan, bebannya tidak.', tags:['work'], choices:[{text:'Kerjain aja',sub:'Aman di kerjaan, hancur di jiwa.',effects:{mental:-13,health:-5,money:0}},{text:'Tawar besok pagi',sub:'Deg-degan, tapi ini batas sehat.',effects:{mental:4,love:2}},{text:'Minta uang lembur',sub:'Berani. Semoga nggak cuma diread.',effects:{money:75000,mental:-5}}]},
 { id:'nikahan', title:'Kondangan Dadakan', scene:'Teman lama yang dulu cuma minjam pulpen tiba-tiba nikah. Kamu diundang.', tags:['social'], choices:[{text:'Datang amplop tipis',sub:'Doa tebal, nominal realistis.',effects:{money:-50000,mental:2,love:3}},{text:'Kirim doa WA',sub:'Murah, tapi agak nggak enakan.',effects:{mental:-3,love:-4}},{text:'Datang incar prasmanan',sub:'Kalau rendang enak, balik modal emosional.',effects:{money:-70000,health:7,mental:8}}]},
 { id:'listrik', title:'Token Listrik Bunyi', scene:'Bip. Bip. Bip. Tengah malam pula. Kosan langsung berasa film horor murah.', tags:['home'], choices:[{text:'Isi 50 ribu',sub:'Lampu nyala, saldo redup.',effects:{money:-50000,mental:4}},{text:'Gelap dulu sampai pagi',sub:'Hemat, tapi nyamuk makin pede.',effects:{mental:-9,health:-2}},{text:'Nebeng colokan',sub:'Diplomasi lorong kos dimulai.',effects:{money:-10000,mental:-2,love:2}}]}
];

export function makeInitial(seed = Date.now() % 999999): GameState { return { day: 1, targetDay: 30, stats: {...initialStats}, history: [], seed, used: [] }; }
function rnd(seed:number){ return Math.abs(Math.sin(seed) * 10000) % 1; }
function hashText(text: string) { return text.split('').reduce((sum, char) => sum + char.charCodeAt(0), 0); }
export function pickEvent(state: GameState): Event {
 const safeStart = ['makan','transport','teman','bonus'];
 const available = events.filter(e=>!state.used.includes(e.id) && (state.day <= 2 ? safeStart.includes(e.id) : true));
 const pool = available.length ? available : events;
 const pressureTags = [state.stats.money < 180000 && 'luck', state.stats.health < 35 && 'health', state.stats.mental < 35 && 'social', state.stats.love < 25 && 'love', state.stats.family < 25 && 'family'].filter(Boolean);
 const weighted = pool.flatMap(e => pressureTags.some(t => e.tags.includes(String(t))) ? [e,e,e] : [e]);
 return weighted[Math.floor(rnd(state.seed + state.day * 37 + state.used.length * 11) * weighted.length)];
}
export function clampStats(s: Stats): Stats { return { money: Math.round(s.money), mental: Math.max(0, Math.min(100, s.mental)), health: Math.max(0, Math.min(100, s.health)), love: Math.max(0, Math.min(100, s.love)), family: Math.max(0, Math.min(100, s.family)), debt: Math.max(0, Math.round(s.debt)) }; }
export function twistForChoice(state: GameState, event: Event, choice: Choice): Partial<Stats> {
 const roll = rnd(state.seed + state.day * 101 + hashText(event.id + choice.text));
 const risk = choice.risk ?? (Object.values(choice.effects).some(v => v < -100000 || v <= -12) ? 0.28 : 0.16);
 if (state.day <= 2 || roll > risk) return {};
 if (roll < risk * 0.25) return { money: -18000, mental: -2 };
 if (roll < risk * 0.5) return { health: -3, mental: -3 };
 if (roll < risk * 0.75) return { love: -3, family: -2 };
 return { money: 24000, mental: 2 };
}
export function applyChoice(state: GameState, event: Event, choice: Choice): GameState { const passive: Partial<Stats> = state.day > 2 ? { money: -12000, mental: -1 } : {}; const twist = twistForChoice(state, event, choice); const stats = clampStats({ ...state.stats, ...Object.fromEntries(Object.keys(state.stats).map(k=>[k, state.stats[k as StatKey] + (passive[k as StatKey] ?? 0) + (choice.effects[k as StatKey] ?? 0) + (twist[k as StatKey] ?? 0)])) } as Stats); const twistNote = Object.keys(twist).length ? ' + hidup ngasih plot twist' : ''; const history = [`Hari ${state.day}: ${event.title} — ${choice.text}${twistNote}`, ...state.history].slice(0,8); const next: GameState = { ...state, day: state.day + 1, stats, history, used: [...state.used, event.id] }; return { ...next, over: getEnding(next) }; }
export function getEnding(s: GameState): EndingKind | undefined { if (s.stats.money < -50000) return 'broke'; if (s.stats.mental <= 0 || s.stats.health <= 0) return 'collapsed'; if (s.stats.love <= 0 && s.stats.family <= 0) return 'ghosted'; if (s.stats.debt >= 1000000) return 'debt'; if (s.day > s.targetDay) return 'payday'; }
export function calculateScore(s: GameState) { const finishBonus = s.day > s.targetDay ? 180 : s.day * 3; const cleanDebtBonus = s.stats.debt === 0 ? 35 : 0; return Math.max(0, Math.round(finishBonus + (s.stats.money/9000) + s.stats.mental + s.stats.health + s.stats.love/2 + s.stats.family/2 - s.stats.debt/18000 + cleanDebtBonus)); }
export function endingText(kind: EndingKind, s: GameState) { const score = calculateScore(s); const map = { payday:['LOLOS SAMPAI GAJIAN','Kamu nyampe gajian. Tidak glamor, tapi hidup. Ini screenshot-able sih.'], broke:['SALDO K.O.','Saldo duluan tumbang. Gapapa, run berikutnya jangan kalap pas merasa aman.'], collapsed:['BADAN MINTA LOGOUT','Kamu terlalu maksa. Kadang pilihan paling OP itu tidur dan makan bener.'], ghosted:['HILANG DARI RADAR','Relasi habis pelan-pelan. Ternyata hemat juga butuh komunikasi.'], debt:['KEPELUK PINJOL','Cairnya cepat, nyeselnya panjang. Ini ending paling horor.'] } as const; return { title: map[kind][0], desc: map[kind][1], score }; }
